# Generated by Django 3.0.8 on 2021-01-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exemplar_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protocol',
            options={'verbose_name': 'protocol', 'verbose_name_plural': 'protocols'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RenameField(
            model_name='protocol',
            old_name='Сomments',
            new_name='Note',
        ),
    ]
