# Generated by Django 3.0.8 on 2021-01-16 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210116_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='Address',
            field=models.CharField(default='', max_length=200, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='Archive',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='archive'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='Description',
            field=models.CharField(default='', max_length=50000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='Genus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Genus'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='Note',
            field=models.CharField(default='', max_length=50000, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='Сoordinates',
            field=models.CharField(default='', max_length=200, verbose_name='coordinates'),
        ),
    ]
