# Generated by Django 3.0.8 on 2021-01-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210116_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='Address',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='Description',
            field=models.CharField(blank=True, default='', max_length=50000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='Note',
            field=models.CharField(blank=True, default='', max_length=50000, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='Сoordinates',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='coordinates'),
        ),
    ]
