# Generated by Django 3.0.8 on 2021-01-19 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210116_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='Made',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='made'),
        ),
        migrations.CreateModel(
            name='ProtocolFindImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='', verbose_name='image')),
                ('ProtocolExemplarFind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ProtocolExemplarFind')),
            ],
        ),
    ]
